[build]
# for WSL Linux
target = ["x86_64-unknown-linux-gnu"]

# for STM32F407G
# target = ["thumbv7em-none-eabihf"]

# for within windows - need to recheck
# target = ["x86_64-pc-windows-msvc"]

# for windows in WSL Linux - need to recheck
# x86_64-w64-mingw32-gcc is required on host machine: https://www.mingw-w64.org/downloads/
# target = ["x86_64-pc-windows-gnu"]

# direct linker to mingw32 windows
[target.x86_64-pc-windows-gnu]
# linker = "x86_64-w64-mingw32-gcc"
# runner = "??emulator??"

